version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: ansarisaif1/probo-backend:latest

  frontend:
    build:
      context: ./frontend
    image: ansarisaif1/probo-frontend:latest

  websocket:
    build:
      context: ./websocket
    image: ansarisaif1/probo-websocket:latest

  consumers:
    build:
      context: ./consumers
    image: ansarisaif1/probo-consumers:latest
