services:
  backend:
    build: 
      context: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  websocket:
    build: 
      context: ./websocket
    env_file:
      - .env
    ports:
      - "9000:9000"
    depends_on:
      - backend
    networks:
      - app-network

  consumers:
    build: 
      context: ./consumers
    env_file:
      - .env
    depends_on:
      - backend
      - websocket
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
