apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "300"
  DATABASE_URL: "sqlite:///./test.db"
  RABBITMQ_HOST: "armadillo.rmq.cloudamqp.com"
  RABBITMQ_QUEUE: "orderbook_queue"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  SECRET_KEY: ZGVDNVVrMjdVYVlLQnBxczRRNDJGbmcybVN5NGwxSnY= # Base64 encoded value of 'deC5Uk27UaYKBpqs4Q42Fng6mSy4l1Jv'
  OTP_SECRET_KEY: SUpURU1OUlZJUkxXT1JDWk1aSFhHWktGR1ZHVUtSQ0VLQTNGSU9DTUdCTFRDV1JVR1pSUQ== # Base64 encoded value of 'IJTEMNRVIRLWORCZMZHXGZKFGVGUKRCEKA3FIOCMGBLTCWRUGZRQ===='
  RABBITMQ_USERNAME: dW1kaWNibms= # Base64 encoded value of 'umdicbnk'
  RABBITMQ_PASSWORD: YU9ISEF1aS1NZjBoc1p5WDdEN2R3X2I3RFJ0czFaVFg= # Base64 encoded value of 'aOHHAui-Mf0hsZyX7D7dW_b7DRts1ZTX'

---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
  - name: backend
    image: ansarisaif1/probo-backend:latest
    envFrom:
    - configMapRef:
        name: app-config
    - secretRef:
        name: app-secrets

---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
  - name: frontend
    image: ansarisaif1/probo-frontend:latest

---
apiVersion: v1
kind: Pod
metadata:
  name: websocket
  labels:
    app: websocket
spec:
  containers:
  - name: websocket
    image: ansarisaif1/probo-websocket:latest

---
apiVersion: v1
kind: Pod
metadata:
  name: consumers
  labels:
    app: consumers
spec:
  containers:
  - name: consumers
    image: ansarisaif1/probo-consumers:latest
    envFrom:
    - configMapRef:
        name: app-config
    - secretRef:
        name: app-secrets
