apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  SECRET_KEY: "deC5Uk27UaYKBpqs4Q42Fng6mSy4l1Jv"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  OTP_SECRET_KEY: "IJTEMNRVIRLWORCZMZHXGZKFGVGUKRCEKA3FIOCMGBLTCWRUGZRQ===="
  DATABASE_URL: "sqlite:///./test.db"
  RABBITMQ_HOST: "armadillo.rmq.cloudamqp.com"
  RABBITMQ_QUEUE: "orderbook_queue"
  RABBITMQ_USERNAME: "umdicbnk"
  RABBITMQ_PASSWORD: "aOHHAui-Mf0hsZyX7D7dW_b7DRts1ZTX"
  RABBITMQ_PORT: "5672"
  ACCESS_TOKEN_EXPIRE_MINUTES: "300"

---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
  - name: backend
    image: ansarisaif1/probo-backend2
    envFrom:
    - configMapRef:
        name: app-config
   
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
  - name: frontend
    image: ansarisaif1/probo-frontend
    envFrom:
    - configMapRef:
        name: app-config

---
apiVersion: v1
kind: Pod
metadata:
  name: websocket
  labels:
    app: websocket
spec:
  containers:
  - name: websocket
    image: ansarisaif1/probo-websocket
    envFrom:
    - configMapRef:
        name: app-config

---
apiVersion: v1
kind: Pod
metadata:
  name: consumers
  labels:
    app: consumers
spec:
  containers:
  - name: consumers
    image: ansarisaif1/probo-consumers
    envFrom:
    - configMapRef:
        name: app-config
